<?php

/**
 * @file
 * Primary module hooks for booking_system module.
 */

/**
 * Implements hook_theme().
 */
function booking_system_theme() {
  $theme = [];
  $theme['booking_config'] = [
    'render element' => 'elements',
    'file' => 'booking_config.page.inc',
    'template' => 'booking_config',
  ];
  $theme['booking_config_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'booking_config.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function booking_system_theme_suggestions_booking_config(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#booking_config'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'booking_config__' . $sanitized_view_mode;
  $suggestions[] = 'booking_config__' . $entity->bundle();
  $suggestions[] = 'booking_config__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'booking_config__' . $entity->id();
  $suggestions[] = 'booking_config__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
