# Schema for the configuration files of the booking_system module.
booking_system.settings:
  type: config_object
  label: 'booking_system settings'
  mapping:
    example:
      type: string
      label: 'Example'
